### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by puccaso** [recantha/EduKit3-RC-Keyboard#1]
```
>>> %Run rc_keyboard.py
Traceback (most recent call last):
  File "/home/pi/Desktop/gure/EduKit3-RC-Keyboard/rc_keyboard.py", line 89
    print 'Left pressed'
                       ^
SyntaxError: Missing parentheses in call to 'print'
>>> 
```

This is the output i'm getting via Thonny, 
Any idea how to fix this? i can't see any parentheses to be honest, so nothing looks 'missing' per se, but still.. any clue?

**Comment by recantha** [comment]
Hi. I *think* that script was originally written in Python 2. If you change it to:
print('Left pressed')
that error should disappear.

**Comment by puccaso** [comment]
Thank you for that 
Now i'm getting this error - 

argh!

```
>>> %Run rc_keyboard.py
Traceback (most recent call last):
  File "/home/pi/Desktop/gure/EduKit3-RC-Keyboard/rc_keyboard.py", line 82, in <module>
    char = getch()
  File "/home/pi/Desktop/gure/EduKit3-RC-Keyboard/rc_keyboard.py", line 61, in getch
    old_settings = termios.tcgetattr(fd)
termios.error: (25, 'Inappropriate ioctl for device')
>>> 
```

**Comment by recantha** [comment]
Try running it from a Terminal rather than Thonny.

**Comment by puccaso** [comment]
aha! ok device needs to charge and its on the other side of the globe right now. will get back to you! thank you for all your time an attention =]

**Comment by recantha** [comment]
No worries :-)
